# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages:
  - pre-commit

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: "v4.0.0"
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml, json5]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0 # or master if you're bold
    hooks:
      - id: interrogate
        args: [--fail-under=95, --generate-badge, docs/interrogate.svg]
        pass_filenames: false # needed if excluding files with pyproject.toml or setup.cfg

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: ["-r", "src"]
        exclude: .*/?tests/.+
